//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_customer()
        {
            this.tb_payment = new HashSet<tb_payment>();
            this.tb_reserve = new HashSet<tb_reserve>();
        }
    
        public int customerCode { get; set; }
        public string customerName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public Nullable<long> mobile { get; set; }
        public string address { get; set; }
        public System.DateTime submitDate { get; set; }
        public Nullable<int> offer_ { get; set; }
        public Nullable<int> adminId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_payment> tb_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reserve> tb_reserve { get; set; }
    }
}
