//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_payment
    {
        public int paymentCode { get; set; }
        public Nullable<int> customerCode { get; set; }
        public int reserveCode { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> payment { get; set; }
        public Nullable<int> offer { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public string paymentType { get; set; }
        public Nullable<int> adminId { get; set; }
    
        public virtual tb_customer tb_customer { get; set; }
        public virtual tb_reserve tb_reserve { get; set; }
    }
}
