//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_personnel()
        {
            this.tb_personnelServiceRel = new HashSet<tb_personnelServiceRel>();
        }
    
        public int personnelCode { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public Nullable<long> nationalCode { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public string workDays { get; set; }
        public long mobile { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> employeDate { get; set; }
        public Nullable<System.DateTime> edittingDate { get; set; }
        public Nullable<int> adminId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_personnelServiceRel> tb_personnelServiceRel { get; set; }
    }
}
