//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_personnelServiceRel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_personnelServiceRel()
        {
            this.tb_reserve = new HashSet<tb_reserve>();
        }
    
        public int psCode { get; set; }
        public int personnelCode { get; set; }
        public int serviceCode { get; set; }
        public int price { get; set; }
        public string description { get; set; }
        public Nullable<int> adminId { get; set; }
    
        public virtual tb_personnel tb_personnel { get; set; }
        public virtual tb_services tb_services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reserve> tb_reserve { get; set; }
    }
}
