//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reserve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_reserve()
        {
            this.tb_payment = new HashSet<tb_payment>();
        }
    
        public int reserveCode { get; set; }
        public Nullable<int> customerCode { get; set; }
        public Nullable<int> psCode { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public string customerName { get; set; }
        public string customerLastName { get; set; }
        public Nullable<long> customerTell { get; set; }
    
        public virtual tb_customer tb_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_payment> tb_payment { get; set; }
        public virtual tb_personnelServiceRel tb_personnelServiceRel { get; set; }
    }
}
