//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_services()
        {
            this.tb_personnelServiceRel = new HashSet<tb_personnelServiceRel>();
        }
    
        public int serviceCode { get; set; }
        public string serviceName { get; set; }
        public string description { get; set; }
        public int timeSpend { get; set; }
        public int price { get; set; }
        public Nullable<int> adminId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_personnelServiceRel> tb_personnelServiceRel { get; set; }
    }
}
