//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beauty_salon_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_salonInfo
    {
        public string salonName { get; set; }
        public string adminName { get; set; }
        public Nullable<long> tell { get; set; }
        public Nullable<int> postalCode { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public byte[] logo { get; set; }
        public string message { get; set; }
        public Nullable<long> fax { get; set; }
    }
}
